// Generated by gencpp from file turtlesim_cleaner/AngleDistanceResponse.msg
// DO NOT EDIT!


#ifndef TURTLESIM_CLEANER_MESSAGE_ANGLEDISTANCERESPONSE_H
#define TURTLESIM_CLEANER_MESSAGE_ANGLEDISTANCERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlesim_cleaner
{
template <class ContainerAllocator>
struct AngleDistanceResponse_
{
  typedef AngleDistanceResponse_<ContainerAllocator> Type;

  AngleDistanceResponse_()
    : complete(false)  {
    }
  AngleDistanceResponse_(const ContainerAllocator& _alloc)
    : complete(false)  {
  (void)_alloc;
    }



   typedef uint8_t _complete_type;
  _complete_type complete;





  typedef boost::shared_ptr< ::turtlesim_cleaner::AngleDistanceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlesim_cleaner::AngleDistanceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AngleDistanceResponse_

typedef ::turtlesim_cleaner::AngleDistanceResponse_<std::allocator<void> > AngleDistanceResponse;

typedef boost::shared_ptr< ::turtlesim_cleaner::AngleDistanceResponse > AngleDistanceResponsePtr;
typedef boost::shared_ptr< ::turtlesim_cleaner::AngleDistanceResponse const> AngleDistanceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlesim_cleaner::AngleDistanceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlesim_cleaner::AngleDistanceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlesim_cleaner::AngleDistanceResponse_<ContainerAllocator1> & lhs, const ::turtlesim_cleaner::AngleDistanceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.complete == rhs.complete;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlesim_cleaner::AngleDistanceResponse_<ContainerAllocator1> & lhs, const ::turtlesim_cleaner::AngleDistanceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlesim_cleaner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim_cleaner::AngleDistanceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim_cleaner::AngleDistanceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlesim_cleaner::AngleDistanceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlesim_cleaner::AngleDistanceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim_cleaner::AngleDistanceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim_cleaner::AngleDistanceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlesim_cleaner::AngleDistanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d8061d2347621a6ed88451e28811cc7";
  }

  static const char* value(const ::turtlesim_cleaner::AngleDistanceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d8061d2347621a6ULL;
  static const uint64_t static_value2 = 0xed88451e28811cc7ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlesim_cleaner::AngleDistanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlesim_cleaner/AngleDistanceResponse";
  }

  static const char* value(const ::turtlesim_cleaner::AngleDistanceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlesim_cleaner::AngleDistanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool complete\n"
"\n"
"\n"
;
  }

  static const char* value(const ::turtlesim_cleaner::AngleDistanceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlesim_cleaner::AngleDistanceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.complete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AngleDistanceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlesim_cleaner::AngleDistanceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlesim_cleaner::AngleDistanceResponse_<ContainerAllocator>& v)
  {
    s << indent << "complete: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.complete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLESIM_CLEANER_MESSAGE_ANGLEDISTANCERESPONSE_H
