// Generated by gencpp from file turtlesim_cleaner/AngleDistanceRequest.msg
// DO NOT EDIT!


#ifndef TURTLESIM_CLEANER_MESSAGE_ANGLEDISTANCEREQUEST_H
#define TURTLESIM_CLEANER_MESSAGE_ANGLEDISTANCEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlesim_cleaner
{
template <class ContainerAllocator>
struct AngleDistanceRequest_
{
  typedef AngleDistanceRequest_<ContainerAllocator> Type;

  AngleDistanceRequest_()
    : angle(0.0)
    , distance(0.0)  {
    }
  AngleDistanceRequest_(const ContainerAllocator& _alloc)
    : angle(0.0)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef double _angle_type;
  _angle_type angle;

   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::turtlesim_cleaner::AngleDistanceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlesim_cleaner::AngleDistanceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AngleDistanceRequest_

typedef ::turtlesim_cleaner::AngleDistanceRequest_<std::allocator<void> > AngleDistanceRequest;

typedef boost::shared_ptr< ::turtlesim_cleaner::AngleDistanceRequest > AngleDistanceRequestPtr;
typedef boost::shared_ptr< ::turtlesim_cleaner::AngleDistanceRequest const> AngleDistanceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlesim_cleaner::AngleDistanceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlesim_cleaner::AngleDistanceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlesim_cleaner::AngleDistanceRequest_<ContainerAllocator1> & lhs, const ::turtlesim_cleaner::AngleDistanceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlesim_cleaner::AngleDistanceRequest_<ContainerAllocator1> & lhs, const ::turtlesim_cleaner::AngleDistanceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlesim_cleaner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim_cleaner::AngleDistanceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim_cleaner::AngleDistanceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlesim_cleaner::AngleDistanceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlesim_cleaner::AngleDistanceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim_cleaner::AngleDistanceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim_cleaner::AngleDistanceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlesim_cleaner::AngleDistanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f5a2ee2aaf541b354d2c44aa9ea8522e";
  }

  static const char* value(const ::turtlesim_cleaner::AngleDistanceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf5a2ee2aaf541b35ULL;
  static const uint64_t static_value2 = 0x4d2c44aa9ea8522eULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlesim_cleaner::AngleDistanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlesim_cleaner/AngleDistanceRequest";
  }

  static const char* value(const ::turtlesim_cleaner::AngleDistanceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlesim_cleaner::AngleDistanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 angle\n"
"float64 distance\n"
;
  }

  static const char* value(const ::turtlesim_cleaner::AngleDistanceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlesim_cleaner::AngleDistanceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AngleDistanceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlesim_cleaner::AngleDistanceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlesim_cleaner::AngleDistanceRequest_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLESIM_CLEANER_MESSAGE_ANGLEDISTANCEREQUEST_H
