// Generated by gencpp from file turtlesim_cleaner/AngleDistance.msg
// DO NOT EDIT!


#ifndef TURTLESIM_CLEANER_MESSAGE_ANGLEDISTANCE_H
#define TURTLESIM_CLEANER_MESSAGE_ANGLEDISTANCE_H

#include <ros/service_traits.h>


#include <turtlesim_cleaner/AngleDistanceRequest.h>
#include <turtlesim_cleaner/AngleDistanceResponse.h>


namespace turtlesim_cleaner
{

struct AngleDistance
{

typedef AngleDistanceRequest Request;
typedef AngleDistanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AngleDistance
} // namespace turtlesim_cleaner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim_cleaner::AngleDistance > {
  static const char* value()
  {
    return "fbefd3cff303f581eade4044f471e589";
  }

  static const char* value(const ::turtlesim_cleaner::AngleDistance&) { return value(); }
};

template<>
struct DataType< ::turtlesim_cleaner::AngleDistance > {
  static const char* value()
  {
    return "turtlesim_cleaner/AngleDistance";
  }

  static const char* value(const ::turtlesim_cleaner::AngleDistance&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim_cleaner::AngleDistanceRequest> should match
// service_traits::MD5Sum< ::turtlesim_cleaner::AngleDistance >
template<>
struct MD5Sum< ::turtlesim_cleaner::AngleDistanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim_cleaner::AngleDistance >::value();
  }
  static const char* value(const ::turtlesim_cleaner::AngleDistanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim_cleaner::AngleDistanceRequest> should match
// service_traits::DataType< ::turtlesim_cleaner::AngleDistance >
template<>
struct DataType< ::turtlesim_cleaner::AngleDistanceRequest>
{
  static const char* value()
  {
    return DataType< ::turtlesim_cleaner::AngleDistance >::value();
  }
  static const char* value(const ::turtlesim_cleaner::AngleDistanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim_cleaner::AngleDistanceResponse> should match
// service_traits::MD5Sum< ::turtlesim_cleaner::AngleDistance >
template<>
struct MD5Sum< ::turtlesim_cleaner::AngleDistanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim_cleaner::AngleDistance >::value();
  }
  static const char* value(const ::turtlesim_cleaner::AngleDistanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim_cleaner::AngleDistanceResponse> should match
// service_traits::DataType< ::turtlesim_cleaner::AngleDistance >
template<>
struct DataType< ::turtlesim_cleaner::AngleDistanceResponse>
{
  static const char* value()
  {
    return DataType< ::turtlesim_cleaner::AngleDistance >::value();
  }
  static const char* value(const ::turtlesim_cleaner::AngleDistanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM_CLEANER_MESSAGE_ANGLEDISTANCE_H
